"""Add products table

Revision ID: 2c6ed9b40598
Revises: 33bfcfa7b012
Create Date: 2026-02-24 13:53:40.210250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c6ed9b40598"
down_revision: Union[str, Sequence[str], None] = "33bfcfa7b012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "phone_number",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("users_phone_number_key"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("users_phone_number_key"),
        "users",
        ["phone_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "users",
        "phone_number",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
