"""Add products table

Revision ID: 33bfcfa7b012
Revises: 3b72585eb234
Create Date: 2026-02-24 13:25:03.315157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33bfcfa7b012"
down_revision: Union[str, Sequence[str], None] = "3b72585eb234"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("users", "email", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("users", "first_name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column("users", "phone_number", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "phone_number", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column("users", "first_name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("users", "email", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("users", "username", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
