"""create initial tables

Revision ID: 3b72585eb234
Revises: 6c2a78276074
Create Date: 2026-02-23 14:29:42.732825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b72585eb234'
down_revision: Union[str, Sequence[str], None] = '6c2a78276074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'telegram_id')
    # ### end Alembic commands ###
