"""Тест

Revision ID: aebba15f7220
Revises: c6d0adf0e57d
Create Date: 2026-02-27 14:23:43.216728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebba15f7220'
down_revision: Union[str, Sequence[str], None] = 'c6d0adf0e57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_wash_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('car_wash_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['car_wash_id'], ['car_washes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_wash_admins')
    # ### end Alembic commands ###
