"""Создание таблицы админов + настройка связей с ними

Revision ID: c6d0adf0e57d
Revises: 57c65ee9fb7f
Create Date: 2026-02-27 13:23:20.359225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d0adf0e57d'
down_revision: Union[str, Sequence[str], None] = '57c65ee9fb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
